# Generated by Django 4.2.7 on 2024-02-27 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comprador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correo", models.EmailField(max_length=255)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("edad", models.PositiveIntegerField()),
                ("calle", models.CharField(max_length=255)),
                ("ciudad", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=255)),
                ("codigo_postal", models.CharField(max_length=10)),
                ("genero", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("marca", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=100)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField()),
                ("texto", models.TextField()),
                ("imagen", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("Puntuacion", models.IntegerField(default="0")),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Lista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField()),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("estado", models.BooleanField(default=False)),
                ("fecha_compra", models.DateField(blank=True, null=True)),
                ("subtotal", models.FloatField()),
                (
                    "comprador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="musicalapp.comprador",
                    ),
                ),
                (
                    "intrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.instrumento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto_final", models.FloatField()),
                ("estado", models.BooleanField(default=False)),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.comprador",
                    ),
                ),
                (
                    "lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.lista",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.comprador",
                    ),
                ),
                (
                    "intrumentos",
                    models.ManyToManyField(
                        related_name="Instrumento_en_carrito", to="musicalapp.lista"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                ("RatingID", models.AutoField(primary_key=True, serialize=False)),
                ("Puntuacion", models.IntegerField()),
                ("Comentario", models.CharField(max_length=255)),
                (
                    "ClienteID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.comprador",
                    ),
                ),
                (
                    "InstrumentosID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.instrumento",
                    ),
                ),
            ],
            options={
                "unique_together": {("InstrumentosID", "ClienteID")},
            },
        ),
    ]
