# Generated by Django 4.2.7 on 2024-03-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("musicalapp", "0003_rename_intrumentos_carrito_listas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrito",
            name="listas",
        ),
        migrations.AddField(
            model_name="carrito",
            name="lista",
            field=models.ManyToManyField(
                related_name="carritos", to="musicalapp.lista"
            ),
        ),
        migrations.AlterField(
            model_name="carrito",
            name="comprador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musicalapp.comprador"
            ),
        ),
    ]
