# Generated by Django 4.2.7 on 2024-03-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicalapp", "0004_remove_carrito_listas_carrito_lista_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carrito",
            name="lista",
        ),
        migrations.AddField(
            model_name="carrito",
            name="intrumentos",
            field=models.ManyToManyField(
                related_name="Instrumento_en_carrito", to="musicalapp.lista"
            ),
        ),
    ]
