# Generated by Django 4.2.7 on 2024-03-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("musicalapp", "0005_remove_carrito_lista_carrito_intrumentos"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorialCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "comprador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.comprador",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="lista",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="lista",
            name="fecha_compra",
        ),
        migrations.DeleteModel(
            name="Transferencia",
        ),
        migrations.AddField(
            model_name="historialcompra",
            name="lista_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="musicalapp.lista"
            ),
        ),
    ]
