# Generated by Django 4.2.7 on 2024-03-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("musicalapp", "0006_historialcompra_remove_lista_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField()),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("subtotal", models.FloatField(default=0)),
                (
                    "comprador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="musicalapp.comprador",
                    ),
                ),
                (
                    "intrumento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musicalapp.instrumento",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historialcompra",
            name="lista_compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="musicalapp.listahistorial",
            ),
        ),
    ]
